# site information
title: Hao Tran
description: Posts

# site settings
url: "https://haothitran.com"
baseurl: "/"
permalink: /posts/:year/:month/:day/:title
repo: https://github.com/haothitran/posts

# build settings
include: ["_pages"]

# author information
author:
  name: Hao Tran
  email: hello@haothitran.com
  website: https://haothitran.com/
  git: https://github.com/haothitran/