# site information
title: Hao Thi Tran
description: Posts

# site settings
url: "https://haothitran.com"
baseurl: "/"
permalink: /:year/:month/:day/:title
repo: https://github.com/haothitran/posts

# build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighting: rouge
highlighter: rouge

# build settings
include: ["_pages"]

# author information
author: Hao Thi Tran
email: hello@haothitran.com
website: https://haothitran.com/
git: https://github.com/haothitran/
